name: GDScript Linting (gdlint)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install gdtoolkit
        run: pip install gdtoolkit

      - name: Run gdlint
        # Wir nutzen "|| true", damit der Workflow immer grün bleibt und nicht fehlschlägt durch Reihenfolge-Fehler bei Klassendefinitionen  oder unbenötigten Parametern.
        # So siehst du die Fehler im Log, aber der Push wird nicht blockiert.
        run: |
          find . -type d \( -path "./addons" -o -path "./tests" \) -prune -o -name "*.gd" -print | xargs -I {} gdlint --disable-rule class-definitions-order --disable-rule unused-argument --disable-rule no-elif-return --disable-rule no-else-return --max-line-length 200 {} || true